### ISSUE TITLE
Error in Quick start Turorial?

### ISSUE THREAD

**Issue by cccntu** [grpc/grpc-web#1009]
I followed the tutorial here: https://grpc.io/docs/platforms/web/quickstart/

And I am getting this error:
![image](https://user-images.githubusercontent.com/31893406/101869565-b6194f80-3bba-11eb-87c6-8916fa9bbc39.png)

❯ docker-compose --version
docker-compose version 1.27.4, build 40524192
❯ docker --version
Docker version 19.03.14, build 5eb3275d40

repo commit version: 45ad6bec6dd8e83d37b219f4b7628ec682bfd091

I am running on remote ubuntu machine, using ssh to forward port 8081 and view the web page on chrome on mac:

Google Chrome | 87.0.4280.88 (Official Build) (x86_64)
-- | --
Revision | 89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}
OS | macOS Version 11.0.1 (Build 20B29)
JavaScript | V8 8.7.220.29

**Comment by stanley-cheung** [comment]
are the docker containers running? Can you double check by running `docker ps -a`?

**Comment by cccntu** [comment]
This is the command in the tutorial:
```
> docker-compose up -d node-server envoy commonjs-client
Recreating grpc-web_common_1 ... done
Recreating grpc-web_prereqs_1 ... done
Recreating grpc-web_commonjs-client_1 ... done
Recreating grpc-web_node-server_1     ... done
Recreating grpc-web_envoy_1           ... done
```

`docker ps -a` output is very long, older rows are manually removed
```
> docker ps -a 
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS                      PORTS                               NAMES
20bb41699d8f        grpcweb/envoy                    "/docker-entrypoint.…"   42 seconds ago      Up 41 seconds               0.0.0.0:8080->8080/tcp, 10000/tcp   grpc-web_en
voy_1
7cd0dc5f9df4        grpcweb/node-server              "docker-entrypoint.s…"   43 seconds ago      Up 42 seconds               0.0.0.0:9090->9090/tcp              grpc-web_no
de-server_1
61bc93938dda        grpcweb/commonjs-client          "docker-entrypoint.s…"   43 seconds ago      Up 42 seconds               0.0.0.0:8081->8081/tcp              grpc-web_co
mmonjs-client_1
8ca05b12da68        grpcweb/prereqs                  "docker-entrypoint.s…"   43 seconds ago      Exited (0) 43 seconds ago                                       grpc-web_prereqs_1
bbc4e219553d        grpcweb/common                   "docker-entrypoint.s…"   43 seconds ago      Exited (0) 43 seconds ago                                       grpc-web_common_1
```

```
❯ docker-compose ps
           Name                         Command               State                  Ports
--------------------------------------------------------------------------------------------------------
grpc-web_common_1            docker-entrypoint.sh node        Exit 0
grpc-web_commonjs-client_1   docker-entrypoint.sh pytho ...   Up       0.0.0.0:8081->8081/tcp
grpc-web_envoy_1             /docker-entrypoint.sh /bin ...   Up       10000/tcp, 0.0.0.0:8080->8080/tcp
grpc-web_node-server_1       docker-entrypoint.sh node  ...   Up       0.0.0.0:9090->9090/tcp
grpc-web_prereqs_1           docker-entrypoint.sh node        Exit 0

```

**Comment by stanley-cheung** [comment]
Looks like you are using Mac. In the example `envoy.yaml` file, we are using `node-server` as the `cluster` `socket_address`, like this: https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/envoy.yaml#L52. The fact that `node-server` works inside a docker container is because of the `--link` parameter we built into the `docker-compose.yml`, like this https://github.com/grpc/grpc-web/blob/master/docker-compose.yml#L57. 

For Mac, that doesn't work. You need to replace that `node-server` in the `socket_address` field in the `envoy.yaml` file with `host.docker.internal`, like it was mentioned here https://github.com/grpc/grpc-web/tree/master/net/grpc/gateway/examples/helloworld#configure-the-proxy.

**Comment by cccntu** [comment]
@stanley-cheung  Thanks for helping me, but I don't think this is the issue, I am actually running on ubuntu as mentioned in my first post.

```
me@mac$ ssh -L 8081:localhost:8081 ubuntu
me@ubuntu$ git clone https://github.com/grpc/grpc-web 
me@ubuntu$ cd grpc-web
me@ubuntu$ docker-compose pull
me@ubuntu$ docker-compose up -d node-server envoy commonjs-client
```
Nevertheless, I tried to edit `net/grpc/gateway/examples/echo/envoy.yaml` accordingly and rebuilt the containers
`docker-compose up --build -d node-server envoy commonjs-client`
The errors are the same.

**Comment by stanley-cheung** [comment]
If you are running on Linux, then you should keep `node-server` as the `socket_address`. 

One thing you might want to try is not to do `docker-compose pull`. Things might have gotten out of sync with the images on docker hub. So you can first delete all those `grpcweb-xxx` docker images first. Then instead of doing `docker-compose pull`, do `docker-compose build common prereqs node-server envoy commonjs-client` and then `docker-compose up node-server envoy commonjs-client`. And see if that helps.

I just tried it in my linux environment with everything (I deleted everything first) and it works here. 

Another thing you might want to check is whether you have any conflicts with those ports used in the example. `8080` is the port in the example where Envoy listens to requests from your browser. `9090` is the port of the actual grpc service. Those are quite common port numbers. Perhaps there might be a conflict there?

**Comment by cccntu** [comment]
> I just tried it in my linux environment with everything (I deleted everything first) and it works here.

Weird. Still doesn't work after deleting and rebuilding.

I used `sudo lsof -i -P -n | grep LISTEN` and only `docker-pr` is listening.

I just tried to use vncserver to use the browser on the ubuntu machine, and it worked!
Using ssh port forward from Mac still doesn't work.

**Comment by cccntu** [comment]
Turns out I also need to forward port 8080. So the js running on mac can connect to localhost(mac) on port 8080, makes sense.
`ssh -L 8081:localhost:8081 -L 8080:localhost:8080 ubuntu`

@stanley-cheung Thanks a lot for your helps! 😄
