### ISSUE TITLE
Problem with deadline after switching to 1.3.0

### ISSUE THREAD

**Issue by kolesnikov-sergey** [grpc/grpc-web#1153]
After upgrading to version 1.3.0, when specifying a deadline, the request is not sent to the server, the promise is not completed. It works correctly without specifying a deadline

Example to reproduce https://github.com/kolesnikov-sergey/deadline-example/blob/master/src/index.js

**Comment by bram-abe** [comment]
> Thanks for the report and sorry for the late reply!
> 
> I'm able to reproduce this issue and will work on a fix soon! 😃

Thank you

**Comment by yoitsro** [comment]
Any news on this? 🙏

**Comment by sampajano** [comment]
> Any news on this? 🙏

Thanks for the interest and sorry for the delay..

After digging deeper it turns out that this is caused by an issue deep down in the Closure library (with `goog.global`) and how it's incompatible with how we're packaging and importing the grpc web library..

While that issue will take a while to fix, i'll make a short-term fix and do a bug fix release soon.

Thanks again for the patience!

**Comment by bram-abe** [comment]
> > Any news on this? 🙏
> 
> Thanks for the interest and sorry for the delay..
> 
> After digging deeper it turns out that this is caused by an issue deep down in the Closure library (with [`goog.global`](https://github.com/google/closure-library/blob/b5188f095a75338eeb09ab899fc94946632f453c/closure/goog/base.js#L47-L56)) and how it's not currently compatible with how we're packaging and importing the grpc-web library..
> 
> While that issue will take a while to fix, i'll make a short-term fix and do a bug fix release soon.
> 
> Thanks again for the patience!

thank you for update, will be waiting for fix release soon.

**Comment by sampajano** [comment]
This issue should've been fixed by the above PR.

I've published a RC release [`1.3.1-rc`](https://www.npmjs.com/package/grpc-web/v/1.3.1-rc) (unfortunately it's tagged as `latest` too 🥲) which contains the fix. Please lemme know if it works (or not).

I'll try to cut a official 1.3.1 release soon too.. :)

Thanks again! :)

**Comment by dalemarchand** [comment]
> This issue should've been fixed by the above PR.
> 
> I've published a RC release [`1.3.1-rc`](https://www.npmjs.com/package/grpc-web/v/1.3.1-rc) which contains the fix. Please try it out and lemme know if it works (or not). 😃
> 
> I'll try to cut a official 1.3.1 release soon too :)
> 
> Thanks again for the patience! :)

I can verify that the published 1.3.1-rc fixes this problem for me
