### ISSUE TITLE
Question on commonjs+dts generation

### ISSUE THREAD

**Issue by visortelle** [grpc/grpc-web#1165]
Config:

![Screen Shot 2021-11-11 at 10 53 57 AM](https://user-images.githubusercontent.com/9302460/141259607-80661e4b-a26c-4e22-83d8-de0182df7511.png)

It generates `.d.ts` file, but imports `.js` file.

![Screen Shot 2021-11-11 at 10 55 00 AM](https://user-images.githubusercontent.com/9302460/141259985-cdbf4041-93ab-4132-8e5d-4a1a8c2a8603.png)

For me looks like a bug.

**Comment by lukasmoellerch** [comment]
I don't think that this is a bug, as this is how typescript handles `.d.ts` type definition files. For every `.d.ts` file there should be a corresponding `.js` file in the same directory. When typescript sees a `require` expression it will also look for a corresponding `.d.ts` file which will be used for type-checking. Because typescript won't modify your path string having a `.d.ts` instead of the `.js` will be a runtime error as the runtime / bundler can't import `.d.ts` files. As per typescript 4.2 it's also not allowed anymore to import `.d.ts` files directly (https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-2.html#dts-extensions-cannot-be-used-in-import-paths).

The `protoc` plugin for `ts` should have generated the corresponding .js file if you have configured it to do so.

**Comment by visortelle** [comment]
@lukasmoellerch 
Gosh. Thank you for your explanation.
Spent half a day configuring a new typescript project.

`request.serializeBinary is not a function`

> WTF? where is a bug. Panic...
 
Completely forgot that both `grpc-web_out` and `js_out`, not only `grpc-web`. 🤦‍♂️🤦‍♂️🤦‍♂️
