### ISSUE TITLE
`get` on repeated field erroring with `TypeError`

### ISSUE THREAD

**Issue by jack-tutor** [grpc/grpc-web#1379]
I have been encountering a problem lately where if I have a repeated field - and the given message does not populate any values in the repeated field - calling the getter for that field on that message will error:

The error looks like:
```
TypeError: Cannot assign to read only property '3' of object '[object Array]'
```
I am using a python backend to generate the messages.

For example, it would occur with protos:
```
message Bar {}

message Foo {
    repeated Bar bars = 1;
}
```
the message created as `Foo(bars=[])` in python
then this:
```
foo.getBarsList()
```
would raise the `TypeError` - but if the message had happened to be created as `Foo(bars=[Bar()])`, then no error would occur. 

I am running `grpc-web 1.4.2`, `grpcio = "^1.56.0"` in python, and protoc `3.20.1`

I do not expect that empty repeated messages are generally broken as this would certainly have been raised as an issue if it was true - but I'm looking for potential causes, debugging steps I should execute, and creating this issue for anyone else that might run into this.

Thanks

**Comment by sampajano** [comment]
@jack-tutor Thanks for the report!

It does sound like a mis-behavior indeed :)

I wonder if you can, help identify the exact line of code which throws that error? 

It would be helpful if you can try not further obfuscate the JS bundle using something like "development" mode (like by replacing [this line](https://github.com/grpc/grpc-web/blob/9d2e24462a7aa1c515ff3a7b3b112a7354dfa3b3/net/grpc/gateway/examples/echo/ts-example/webpack.config.js#L2)).

It's ok if the line is already obfuscated, but at least we can confirm where the error is coming from. (I'd guess it's happening in the protobuf-javascript) library, since from what i can tell from my manual test, the generated code would simply call into the `getRepeatedWrapperField` function, like below:

```js
/**
 * repeated Bar bars = 3;
 * @return {!Array<!proto.grpc.gateway.testing.Bar>}
 */
proto.grpc.gateway.testing.EchoResponse.prototype.getBarsList = function() {
  return /** @type{!Array<!proto.grpc.gateway.testing.Bar>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.grpc.gateway.testing.Bar, 3));
};
```

Which is implemented below:

https://github.com/protocolbuffers/protobuf-javascript/blob/e1a52f9a897653985b0649cca17615cb1b0eb3b7/message.js#L1262-L1277

**Comment by sampajano** [comment]
Closing for now due to inactivity. Feel feel to re-open with more details! Thanks!
