### ISSUE TITLE
Client throws base64 encoding error on RPC call

### ISSUE THREAD

**Issue by atecce** [grpc/grpc-web#183]
Given the following sample web page 

```html
<html>
    <meta charset="utf-8"/>
    <script src="compiled.js"></script>
    <script>

        var client = new proto.API.ServiceClient('127.0.0.1:50051');

        var query = new proto.API.Query();
        query.setMessagesList(["testing", "1", "2", "3"]);

        client.get(query, {}, function(error, response) {
            if (error) {
                console.log(error);
            } else {
                console.log(reponse.getResponse());
            }
        });
    </script>
</html>
```

A JavaScript error is thrown at `client.get` with the following stacktrace.

```
Error: Unknown base64 encoding at char: <
compiled.js:429:210
c
http://localhost:3000/compiled.js:429:210
goog.crypt.base64.decodeStringInternal_
http://localhost:3000/compiled.js:429:312
goog.crypt.base64.decodeStringToUint8Array
http://localhost:3000/compiled.js:428:277
module$contents$grpc$web$GrpcWebClientReadableStream_GrpcWebClientReadableStream/<
http://localhost:3000/compiled.js:432:237
goog.events.EventTarget.prototype.fireListeners
http://localhost:3000/compiled.js:279:296
goog.events.EventTarget.dispatchEventInternal_
http://localhost:3000/compiled.js:281:475
goog.events.EventTarget.prototype.dispatchEvent
http://localhost:3000/compiled.js:276:274
goog.net.XhrIo.prototype.onReadyStateChangeHelper_
http://localhost:3000/compiled.js:401:485
goog.net.XhrIo.prototype.onReadyStateChangeEntryPoint_
http://localhost:3000/compiled.js:400:491
goog.net.XhrIo.prototype.onReadyStateChange_
http://localhost:3000/compiled.js:400:387
<anonymous> self-hosted:975:17
```

I'm a little puzzled by the method signature of `client.get`. Are there any docs which point me in the direction of what the empty object in the second parameter is doing?

**Comment by stanley-cheung** [comment]
Can you show me your .proto definition please?

**Comment by atecce** [comment]
sure thing! omw home now. i’m mobile.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by stanley-cheung** [comment]
Just to confirm, you have compiled our nginx module and run that as proxy. The :50051 port is your nginx port right? And have you tried to run the Echo example that comes with this repo?

Btw, the 2nd parameter of the generated RPC call is `metadata`, may be relevant if your server is expecting them. Otherwise you can leave it empty.

**Comment by atecce** [comment]
no. i’m not running the nginx proxy. just hitting a service defined in C#

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by stanley-cheung** [comment]
Yea that won't work. grpc-web currently cannot talk to a gRPC backend server directly because of various browser limitations. So the grpc-web client currently talks a "grpc-web" protocol, which needs translation. A reference proxy implementation is included in this repo as a custom module of Nginx. So you need to compile the Nginx that comes with this repo so that the grpc-web client request can be translated into a gRPC call to the backend, and vice versa in the other direction.

**Comment by atecce** [comment]
heh. that will do it. thanks so much! i’ll get to work on that

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by stanley-cheung** [comment]
See the Echo example here: https://github.com/grpc/grpc-web/tree/master/net/grpc/gateway/examples/echo

**Comment by jonahbron** [comment]
@atecce There's also a GRPC-Web proxy implemented in Go by Improbable, available here:

https://github.com/improbable-eng/grpc-web/tree/master/go/grpcwebproxy

I found it a bit easier to set up.

**Comment by atecce** [comment]
heh. yeah! static binaries. such is the Way of Unix :D
