### ISSUE TITLE
Need more demo's and documentation

### ISSUE THREAD

**Issue by gregkeys** [grpc/grpc-web#295]
I'm having a terrible time reasoning about grpc-web because the README.md doesnt really line up with the example.

it seems really simple at first, just define a proto with Echo, EchoRequest, EchoResponse but when working through the example the proto contains significantly more api definition.

it would be nice to have a working demo that matches the README.md just as a starting point. also is there any documentation for grpc-web or source code available to see what methods are available and how to implement things, for example how do you implement tls, can I provide a ca file or do I just need to connect to a tls secured endpoint.

My goal is to use web components for the front end that use the same proto as a micro service on the backend, so that we can have both server and client in the same repo to simplify our workflow, testing and deployment.

**Comment by johanbrandhorst** [comment]
I think as far as TLS goes it's just a matter of talking to a TLS endpoint, the browser handles all the certificate stuff.

**Comment by stanley-cheung** [comment]
Agreed that the examples and documentations can be improved. The original goal was to have something a little nicer so that first-time user can interact with on a "sort-of" chat app on a browser. So yes there are some unnecessary jQuery stuff sprinkled in and I agree that there's a bit of a bloat by now. Agreed that we should simplify the main demo and have this Echo demo be a more "advanced" example.

As for TLS, here's an example where a user configured that with Kubernetes:
https://github.com/salrashid123/grpc_web_with_gke

This is another perhaps simpler example with gRPC-Web as well:
https://github.com/viglesiasce/echo-grpc-web-python

**Comment by hunnain** [comment]
Greg you right.Stanley please provide more docs to understand grpc-web it is more complicate to learn and use and you are using go language but most developers use javascript nodejs expressjs and python.You also need to provide dos for reactjs and react-native.
