### ISSUE TITLE
How do I use protoc-gen-grpc-web on Windows?

### ISSUE THREAD

**Issue by sandersaares** [grpc/grpc-web#342]
`$ sudo make install-plugin` in the readme is clearly a Linux command. I wish to use this tool on Windows. What do I do?

**Comment by johanbrandhorst** [comment]
Yeah I think we need to include binary generators with the releases. Indeed, version 1.0 should probably have some pre-built binaries included with it to make adoption easier.

**Comment by stanley-cheung** [comment]
Building the plugin on Windows is currently supported via [Bazel](https://bazel.build/). See this comment: https://github.com/grpc/grpc-web/issues/250#issuecomment-414479303

**Comment by johanbrandhorst** [comment]
Is there a plan to release pre-built binaries of the generator plugin? I think it will lower the barrier to entry significantly.

**Comment by Yannic** [comment]
@stanley-cheung This isn't the first time someone asks about building the plugin on Windows. I think we should add something to the readme to clarify that Bazel is required to build on Windows.

Or we could even go further and say to always build with Bazel regardless of the platform, which would also eliminate the need to install `protoc` separately. Of course, it would still be possible to run `protoc` as before. WDYT?

```
bazel build @com_google_protobuf//:protoc //javascript/net/grpc/web:protoc-gen-grpc-web

./bazel-bin/external/com_google_protobuf/protoc \
  -I=$DIR \
  --plugin=protoc-gen-grpc=bazel-bin/javascript/net/grpc/web/protoc-gen-grpc-web \
  --js_out=...  \
  --grpc-web_out=... \
  echo.proto
```

**Comment by sandersaares** [comment]
Realistically speaking, without a binary release using this tool is a no-go for all of my potential use cases.

Having to compile one's development tools is just not an acceptable setup scenario in the Windows world.

**Comment by stanley-cheung** [comment]
Yes we should be a pre-compiled release of the protoc plugin. Sorry we just haven't gotten around to it yet. Will certainly work on it asap.

**Comment by pumano** [comment]
@stanley-cheung amazing! I'm waiting for it too

**Comment by tam15** [comment]
Hello, I'm trying to use bazel to compile this plugin however I'm getting a "no such package" error, has this changed location since @Yannic  's solution?

$ bazel build @com_google_protobuf//:protoc //javascript/net/grpc/web:protoc-gen-grpc-web
ERROR: python.exe not found on PATH
Loading:
Loading: 0 packages loaded
ERROR: Skipping '//javascript/net/grpc/web:protoc-gen-grpc-web': no such package 'javascript/net/grpc/web': BUILD file not found on package path
WARNING: Target pattern parsing failed.
ERROR: no such package 'javascript/net/grpc/web': BUILD file not found on package path
INFO: Elapsed time: 0.404s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by stanley-cheung** [comment]
The pre-built binaries for the `protoc-gen-grpc-web` plugin for Windows has been uploaded along with the latest 1.0.3 release. Please check it out.

https://github.com/grpc/grpc-web/releases

**Comment by Type1J** [comment]
The released binaries seem to not work in Docker for Windows base images with servercore or nanocore. It's a 64-binary, but it's missing some .dll dependencies (Error 3221225781).
