### ISSUE TITLE
Field names of generated Typescript (typings) objects are UpperCamelCase

### ISSUE THREAD

**Issue by maeb** [grpc/grpc-web#428]
If https://github.com/protocolbuffers/protobuf/pull/5449 gets merged it would be convenient if the generator generated the names of object fields using lowerCamelCase.

The `JSFieldName` function used for formatting calls `ToUpperCamelCase` which only makes sense when generating the getter/setter functions (getUpperCamelCaseFunctionName/setUpperCamelCaseFunctionName).

https://github.com/grpc/grpc-web/blob/09604c483732a0cabd93b5658aad0b380ff23a29/javascript/net/grpc/web/grpc_generator.cc#L672)

**Comment by johanbrandhorst** [comment]
This bug is causing incompatibilities when using the grpc-web typescript typings with well known types. For example, for the `google.protobuf.Duration` type, the following is generated:

```typescript
export namespace Duration {
  export type AsObject = {
    Seconds: number;
    Nanos: number;
  }
}
```

This causes compilation errors since the official typings for the well known duration type define it as follows:
(ref: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/6537c15a2877a99b2eee9875e7644b2344ad7973/types/google-protobuf/google/protobuf/duration_pb.d.ts#L20)
```typescript
export namespace Duration {
  export type AsObject = {
    seconds: number,
    nanos: number,
  }
}
```

**Comment by johanbrandhorst** [comment]
@stanley-cheung Could we have a minor release of the generator with this change?

**Comment by stanley-cheung** [comment]
@johanbrandhorst Yes, I am working on a github x internal sync, which will export some code generator changes as well. Will do a release after that.

**Comment by linuxexp** [comment]
+1 for the issue.
