### ISSUE TITLE
Release process (CI/CD?)

### ISSUE THREAD

**Issue by TBoshoven** [grpc/grpc-web#456]
The latest release, 1.0.3, was done in November.
We've reached February and a lot of issues have been fixed.

Since the recommended (and most convenient) way of using gRPC-Web is to use a released version, it would be nice to have a new release.
More structurally, it would be great if we could get a release whenever something is merged to master.

**Comment by stanley-cheung** [comment]
Yea it has been a while. We are still working on it. In the next few months hopefully we can get this process down more efficiently, so that we can do releases more frequently.

**Comment by TBoshoven** [comment]
What is the work required to make a new release possible?
Is it something we can help with?

**Comment by stanley-cheung** [comment]
Again sorry for the late reply. The complexity lies in the import process that we have to keep the code in sync between code here in Github with our internal process. With a large number of changes, it introduces quite a lot of conflicts and new test breakage. I am currently debugging and resolving a number of test failures that I might need to revert a number of PRs. 

In the mean time, I had been trying to figure out how to prevent this headache in the future. Solution probably lies somewhere between "doing this more frequently" so that there is less chance of a conflict. And adding more script so that I can do this more efficiently. 

Sorry for the delay again. I am actively working on this.

**Comment by stanley-cheung** [comment]
Closing this. We just released `1.0.4` and things appear to be stable. The code are in sync with the internal codebase as of this point. We will try to not let things get as out of hand as the previous release and release more often as possible.
