### ISSUE TITLE
spec: capitalization of header names to improve interoperabilty

### ISSUE THREAD

**Issue by kewde** [grpc/grpc-web#696]
Hello,

There seems to be an issue with the capitalization of the header names. It seems that everything under this repository expects lowercase capitalization for the header names.
This is a bit odd, seeing that header names are usually capitalized on each word.
`Grpc-Message` vs `grpc-message`.

The golang proxy of improbable engineering returns the former, `Grpc-Message` and `Grpc-Status` which causes the error handling to fail in the grpc-web javascript client. The callback for the request is never called if an error is returned. Manually editing these to include the caps solves the issue.

Note: I believe this might also the issue causing #415

**Comment by bamnet** [comment]
I just ran into this. [bufbuild/connect-go](https://github.com/bufbuild/connect-go/) returns the capitalized headers, but the dart grpc (web) client expects them to be lowercase. 

Opened bufbuild/connect-go/issues/453 to explore this on the connect-go side, but it would be great if the spec was clear if these trailers should work like HTTP headers which are case-insensitive (therefore fixed in clients) or should be case sensitive (and therefore fixed in servers).

**Comment by bamnet** [comment]
re improbable: I believe this was fixed in improbable-eng/grpc-web#228 where they switched to lowercase.

**Comment by sampajano** [comment]
Thanks for the discussion!

Per my understanding HTTP headers are supposed to be case-insensitive. So if we're having compatibility issues due to capitalization it's probably a bug on our end. Although as long as all mainstream implementations are using lower case, i guess this isn't high priority to fix :)

I'll close for now (since this was 2019). Please re-open know if there's any interoperability issues due to casing. Thanks!
