### ISSUE TITLE
[QUESTION] Using protobuf.js instead of google-protobuf 

### ISSUE THREAD

**Issue by ramsrib** [grpc/grpc-web#840]
Is it possible to use [protobuf.js](https://github.com/protobufjs/protobuf.js) instead of [google-protobuf](https://github.com/protocolbuffers/protobuf/tree/master/js) library with `grpc-web`? 

One of main reason behind this question is that `google-protobuf` increases the js chunk size significantly. (like ~400kb)

Couple of advantages of `protobuf.js`:
- very small bundle size (~19kb)
- protobuf.js is a pure javascript implementation

**Comment by stanley-cheung** [comment]
Currently there is no plan to support protobuf.js. See #80

**Comment by faameunier** [comment]
So I came across the same idea.

I played a bit with the generated code of both `grpc-web` and `protobufjs`.
Turns out, you can hack your way through and use `protobufjs` for serializing.

**4 (not so easy) steps**:
1. Generate only service files with `protoc`
2. Generate all but service files with `pbjs`
3. Rename pbjs files and place them as if they were generated by protoc
4. Edit protoc's service files to use `.encode` / `.decode` of pbjs instead of `.serializeBinary` / `.deserializeBinary`of expected classes.

No idea how much this breaks in typescript, it is **barely** tested. 

Here is a bash script that does all this automatically (I suck at bash scripting).
```sh
#build.sh
PKG_PATH="./src/gen"
PROTO_PATH="./proto"

rm -rf $PKG_PATH
mkdir $PKG_PATH
protoc -I=proto --grpc-web_out=import_style=commonjs,mode=grpcwebtext:$PKG_PATH  $PROTO_PATH/**/*.proto $PROTO_PATH/*.proto

sed -i.old '1 i\
/* eslint-disable */
' src/gen/**/*.js
rm src/gen/**/*.old


PKGS=$(find $PROTO_PATH -type d)
for PKG in $PKGS; do
	echo "Creating pbjs objects for " $PKG
    MODULES=$(find $PKG -maxdepth 1 -iname "*.proto" | sort)
    echo $PKG
    for MODULE in $MODULES; do
    	OUT_JS=${MODULE%'.proto'}_pb.js
    	OUT_JS=$PKG_PATH${OUT_JS#$PROTO_PATH}
        pbjs -t static-module -r proto --no-service -w commonjs $MODULE -o $OUT_JS --path $PROTO_PATH
    done
done

sed -i.old -e 's/\.serializeBinary/\.constructor\.encode(request)\.finish/g' $PKG_PATH/*_web_pb.js
sed -i.old -e 's/\.serializeBinary/\.constructor\.encode(request)\.finish/g' $PKG_PATH/**/*_web_pb.js
sed -i.old -e 's/\.deserializeBinary/\.decode/g' $PKG_PATH/*_web_pb.js
sed -i.old -e 's/\.deserializeBinary/\.decode/g' $PKG_PATH/**/*_web_pb.js

sed -i.old -e 's/protobufjs-dbx\/minimal/protobufjs\/minimal/g' $PKG_PATH/*_pb.js
sed -i.old -e 's/protobufjs-dbx\/minimal/protobufjs\/minimal/g' $PKG_PATH/**/*_pb.js

rm $PKG_PATH/*.old
rm $PKG_PATH/**/*.old
```

Best of both worlds but very likely to break at any point in time.
