### ISSUE TITLE
Remove Nginx gateway code from this repo

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc-web#870]
The custom Nginx grpc-web gateway (code under the `net/grpc/gateway` directory) has not been officially supported since Envoy has become the default proxy for grpc-web. We are going to remove the code from this repo some time soon.

**Comment by maxnilz** [comment]
Currently, because the envoy does not support compress the grpc-web content type,
I can see one of the benefits of using nginx as the grpc-web proxy, for the grpc-web unary call, in case of we want to utilize the gzip function to compress the bas64 data before sending them to the wire so that we can save bandwidth for the big response.
